######################################################################
# Automatically generated by qmake (2.01a) ?r. mar 25 14:55:17 2009
######################################################################

TEMPLATE = lib
CONFIG += plugin
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ../.

# Input
HEADERS += fooalsaplugin.hpp fooalsastruct.hpp
SOURCES += fooalsaplugin.cpp fooalsastruct.cpp
