######################################################################
# Automatically generated by qmake (2.01a) czw. kwi 9 17:58:20 2009
######################################################################

TEMPLATE = lib
CONFIG += plugin
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fooalsaoption.hpp \
           fooalsaplugin.hpp \
           fooalsastruct.hpp \
           ../fooplugininterfaces.hpp
SOURCES += fooalsaoption.cpp fooalsaplugin.cpp fooalsastruct.cpp
